---
# Main playbook - using roles

- name: Configure team machines with vulnerabilities
  hosts: team
  become: yes
  gather_facts: yes
  serial: 0
  roles:
    - role: roles/common
    - role: roles/users

- name: Set up Kali with offensive tools
  hosts: kali
  become: yes
  gather_facts: yes
  serial: 0
  roles:
    - role: roles/kali

- name: Configure Web server
  hosts: debian_web
  become: yes
  gather_facts: yes
  serial: 0
  roles:
    - role: roles/web
