---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Update apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      
    - name: Install required packages
      ansible.builtin.package:
        name:
          - sudo
          - python3
        state: present
  
  roles:
    - role: users
