---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Verify users exist
      ansible.builtin.command: "grep '^{{ item.username }}:' /etc/passwd"
      register: users_exist
      loop: "{{ interesting_users }}"
      changed_when: false
      failed_when: users_exist.rc != 0
      
    - name: Verify users have home directories
      ansible.builtin.stat:
        path: "/home/{{ item.username }}"
      register: user_homes
      loop: "{{ interesting_users }}"
      failed_when: not user_homes.results[0].stat.exists or not user_homes.results[1].stat.exists or not user_homes.results[2].stat.exists