---
galaxy_info:
  role_name: users
  namespace: ncae
  author: ncae_admin
  description: Configuration for interesting user accounts with preset credentials
  company: NCAE

  license: MIT

  min_ansible_version: "2.10"

  platforms:
    - name: Debian
      versions:
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"

  galaxy_tags:
    - users
    - accounts
    - security
    - training

dependencies: []
