---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      
    - name: Install required packages for tests
      ansible.builtin.apt:
        name:
          - sudo
          - apache2
          - php
          - php-mysql
        state: present
  
  roles:
    - role: web
