---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Verify root password is set
      ansible.builtin.command: "grep '^root:' /etc/shadow"
      register: root_password_result
      changed_when: false
      failed_when: root_password_result.rc != 0
      
    - name: Verify blueteam user exists
      ansible.builtin.command: "grep '^blueteam:' /etc/passwd"
      register: blueteam_exists
      changed_when: false
      failed_when: blueteam_exists.rc != 0
      
    - name: Verify redteam user exists
      ansible.builtin.command: "grep '^redteam:' /etc/passwd"
      register: redteam_exists
      changed_when: false
      failed_when: redteam_exists.rc != 0
      
    - name: Check if SSH configuration allows root login
      ansible.builtin.command: "grep 'PermitRootLogin yes' /etc/ssh/sshd_config"
      register: ssh_root_login
      changed_when: false
      failed_when: ssh_root_login.rc != 0
      
    - name: Check if malicious service files exist
      ansible.builtin.stat:
        path: "/etc/systemd/system/{{ item }}.service"
      register: service_files
      loop:
        - "user-default"
        - "php"
      failed_when: not service_files.results[0].stat.exists or not service_files.results[1].stat.exists